### Numpy
Notebook cuyo objetivo es proporcionar una introducción sólida fundamentos de Numpy, sus aplicaciones en computación númerica, Machine Learning, Data Science, y un largo etcétera. Nos proporciona estructuras de datos eficientes para la manipulación de arreglos u otras operaciones propiamente matemáticas.

In [10]:
import numpy as np
# Array unidimensional
array_2 = np.array([7, 77, 777])
print(type(array_2))

<class 'numpy.ndarray'>


In [11]:
# Impresión de la forma (.shape)
print(type(array_2.shape))
print(array_2.shape)
print(array_2)

<class 'tuple'>
(3,)
[  7  77 777]


In [13]:
# Acceso a elementos mediante indices
print(array_2[0])
print(array_2[1])
print(array_2[2])
array_2[2] = 4 # Reasignación de elemento dentro del arreglo
print(array_2[2])

7
77
777
4


In [18]:
# Array multidimensional
array_3 = np.array([[11,12,13],  [22,23,24],  [22,23,24],  [22,23,24]])
print("La forma de este array es: ", array_3.shape)

La forma de este array es:  (4, 3)


In [21]:
print("Así accedo en un array de dos dimensiones", array_3[0,2])
print("Array completo")
print(array_3)


Así accedo a un valor de este array de dos dimensiones 13
Así imprimo el array completo
[[11 12 13]
 [22 23 24]
 [22 23 24]
 [22 23 24]]


$ I^{n \times n} =
\left( \begin{array}{cccc}
 11 & 12 & 13  \\
 22 & 23 & 24  \\
 35 & 36 & 37  \\
\end{array} \right) $


### Distintas maneras de crear nd arrays

In [22]:
#crear array lleno de ceros
ej1 = np.zeros((1080,1920,3))
print(ej1)


[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 ...

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [23]:
#creamos un array lleno de un valor determinado (floats por ejemplo)
ej2 = np.full((20,20,3), 9.1)
print(ej2)

[[[9.1 9.1 9.1]
  [9.1 9.1 9.1]
  [9.1 9.1 9.1]
  ...
  [9.1 9.1 9.1]
  [9.1 9.1 9.1]
  [9.1 9.1 9.1]]

 [[9.1 9.1 9.1]
  [9.1 9.1 9.1]
  [9.1 9.1 9.1]
  ...
  [9.1 9.1 9.1]
  [9.1 9.1 9.1]
  [9.1 9.1 9.1]]

 [[9.1 9.1 9.1]
  [9.1 9.1 9.1]
  [9.1 9.1 9.1]
  ...
  [9.1 9.1 9.1]
  [9.1 9.1 9.1]
  [9.1 9.1 9.1]]

 ...

 [[9.1 9.1 9.1]
  [9.1 9.1 9.1]
  [9.1 9.1 9.1]
  ...
  [9.1 9.1 9.1]
  [9.1 9.1 9.1]
  [9.1 9.1 9.1]]

 [[9.1 9.1 9.1]
  [9.1 9.1 9.1]
  [9.1 9.1 9.1]
  ...
  [9.1 9.1 9.1]
  [9.1 9.1 9.1]
  [9.1 9.1 9.1]]

 [[9.1 9.1 9.1]
  [9.1 9.1 9.1]
  [9.1 9.1 9.1]
  ...
  [9.1 9.1 9.1]
  [9.1 9.1 9.1]
  [9.1 9.1 9.1]]]


In [24]:
#creando un array de 2x2 condiagonal en "unos" y el resto cero
ej3 = np.eye(7,7)
print(ej3)

[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]


In [25]:
#creando un array de "unos"
ej4 = np.ones((10,7,2))
print(ej4)

[[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]]


In [26]:
# creamos un array de flotantes aleatorios entre 0 y 1
ej5 = np.random.random((5,5))
print(ej5)

[[0.08376481 0.68487028 0.78664704 0.37150403 0.16819783]
 [0.04984348 0.41111523 0.69610869 0.65759328 0.32334267]
 [0.20235632 0.34794585 0.28233444 0.33779702 0.55650427]
 [0.79594911 0.7001144  0.00415788 0.16959442 0.54866565]
 [0.15575832 0.17485195 0.03275288 0.17843955 0.93493396]]



### Slicing
El "slicing" en NumPy se refiere a la técnica de extraer porciones de un arreglo multidimensional. Es una forma eficiente y potente de acceder y manipular datos en arreglos NumPy. El slicing se realiza mediante la especificación de rangos a lo largo de cada dimensión del arreglo.

In [39]:

# Crear un arreglo multidimensional de ejemplo
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr)
print('')
# Slicing en una dimensión
result_1d = arr[1, :]  # Obtener la segunda fila completa
# Resultado: array([4, 5, 6])
print(result_1d)
print('')

# Slicing en dos dimensiones
result_2d = arr[:2, 1:]  # Obtener las dos primeras filas y las columnas de la segunda en adelante
# Resultado: array([[2, 3],
#                  [5, 6]])
print(result_2d)
print('')

# Slicing con pasos
result_step = arr[::2, ::2]  # Obtener cada segunda fila y columna
# Resultado: array([[1, 3],
#                  [7, 9]])
print(result_step)
print('')


[[1 2 3]
 [4 5 6]
 [7 8 9]]

[4 5 6]

[[2 3]
 [5 6]]

[[1 3]
 [7 9]]



In [27]:
un_array = np.array([[11,12,13,14,15,16], [21,22,23,24,25,26], [31,32,33,34,35,36],[41,42,43,44,45,46]])
print(un_array)

[[11 12 13 14 15 16]
 [21 22 23 24 25 26]
 [31 32 33 34 35 36]
 [41 42 43 44 45 46]]


In [33]:
# Slice de 2 x 2 a partir de "un_array"
un_slice = un_array[:2,1:3]
print(un_slice)

[[112  13]
 [ 22  23]]


In [34]:
# Valor fila 0 columna 0 del slice
# El slice genera un nuevo índice
print("Slice:", un_slice[0, 0])

Slice: 112


In [35]:
# Suma de 100 al valor de la posicion (0,0) del slice
un_slice[0,0] += 100
print("Slice:", un_slice[0, 0])

Slice: 212


In [31]:
#hora imprimamos la posición (0,1) del array original,
print("Array original:", un_array[0, 1])

Array original: 112


¿cómo, pero si al array original no lo tocamos?

In [41]:
# Un slice, no es más que un puntero o acceso directo al array original,\
# Si modificamos el slice en realidad estaremos modificando el array original.
print(un_array)
type(un_slice)

[[ 11 212  13  14  15  16]
 [ 21  22  23  24  25  26]
 [ 31  32  33  34  35  36]
 [ 41  42  43  44  45  46]]


numpy.ndarray

¿Y si necesitasemos tener un nuevo array a partir de un slice?

In [42]:
nuevo_array = np.array(un_slice)
print(nuevo_array)

[[212  13]
 [ 22  23]]


In [43]:
# Una sola fila, entonces el slice será unidimensional.
row_rank1 = un_array[1, :]
print(row_rank1, row_rank1.shape)

[21 22 23 24 25 26] (6,)


In [44]:
# Lo mimso podemos hacer con una columna
row_rank1 = un_array[:, 1]
print(row_rank1, row_rank1.shape)

[212  22  32  42] (4,)


### Array de índices
A veces es útil, preparar una serie de índices en un array, para luego utilizarlos para operar sobre otro.

In [45]:
# Creamos un nuevo array
array_a = np.array([[11,12,13], [21,22,23], [31,32,33], [41,42,43]])
print(array_a)
print(array_a.shape)

[[11 12 13]
 [21 22 23]
 [31 32 33]
 [41 42 43]]
(4, 3)


In [46]:
# Creamos 2 arrays con números enteros que usaremos como indices
cols = np.array([0,1,2,0])
rows = np.arange(4)
print("Elegimos estos índices para filas ->", rows)
print("Elegimos estos índices para columnas ->", cols)


Elegimos estos índices para filas -> [0 1 2 3]
Elegimos estos índices para columnas -> [0 1 2 0]


In [48]:
# índices tomando uno de cada array, pares
for row,col in zip(rows,cols):
    print('({}, {})'.format(row, col))

(0, 0)
(1, 1)
(2, 2)
(3, 0)


In [50]:
# Seleccionar un elemento de cada fila, hacemos de esta manera
print('Los valores contenidos en los índices son: ', array_a[rows, cols])

Los valores contenidos en los índices son:  [11 22 33 41]


In [51]:
# Operar con los valores seleccionados
print(array_a)
array_a[rows, cols] += 1000
print(array_a)

[[11 12 13]
 [21 22 23]
 [31 32 33]
 [41 42 43]]
[[1011   12   13]
 [  21 1022   23]
 [  31   32 1033]
 [1041   42   43]]


### Indexado Booleano
Indexado booleano para cambiar elementos

In [ ]:
# Creamos un array de 3x2
array_b = np.array([[11,12], [21, 22], [31, 32]])
print(array_b)
print("______________")
print(array_b.shape)

[[11 12]
 [21 22]
 [31 32]]
______________
(3, 2)


In [ ]:
# Crear un filtro es muy facil en numpy
filtro = (array_b > 15)
filtro

array([[False, False],
       [ True,  True],
       [ True,  True]])

In [ ]:
# Entonces ahora podemos aplicar el filtro a nuestro array
filtrado = array_b[filtro]
print(filtrado)

[21 22 31 32]


In [ ]:
# No es necesario primero crear el filtro y luego aplicarlo, podemos hacerlo al unísono
print(array_b[(array_b % 2 == 0)])

[12 22 32]


El uso principal de este tipo de filtros es el de poder modificar los valores del array que cumplan cierto criterio

In [ ]:
array_b[array_b % 2 == 0] += 1000
print(array_b)

[[  11 1012]
 [  21 1022]
 [  31 1032]]


### Tipos de datos en arrays

In [ ]:
# En este caso python se encarga de asignar el tipo de dato
ej1 = np.array([11, 12])
print(ej1.dtype)

int64


In [ ]:
# Python asigna el tipo de dato
ej2 = np.array([11.0, 12.0])
print(ej2.dtype)

float64


In [ ]:
# También puedo forzar el tipo de dato expresándolo de manera explícita
ej3 = np.array([11, 21], dtype=np.float64)
print(ej3.dtype)

float64


In [ ]:
# Si lo necesitáramos podríamos forzar flotantes a enteros
ej4 = np.array([11.1,12.7], dtype=np.int64)
print(ej4.dtype)
print()
print(ej4)

int64

[11 12]


### Operaciones Aritméticas

In [ ]:
x = np.array([[111,112],[121,122]], dtype=np.int)
y = np.array([[211.1,212.1],[221.1,222.1]], dtype=np.float64)

print(x)
print()
print(y)

[[111 112]
 [121 122]]

[[211.1 212.1]
 [221.1 222.1]]


In [ ]:
# resta
print(x - y)
print()
print(np.subtract(x, y))

[[-100.1 -100.1]
 [-100.1 -100.1]]

[[-100.1 -100.1]
 [-100.1 -100.1]]


In [ ]:
# multiplicación
print(x * y)
print()
print(np.multiply(x, y))

[[23432.1 23755.2]
 [26753.1 27096.2]]

[[23432.1 23755.2]
 [26753.1 27096.2]]


In [ ]:
# división
print(x / y)
print()
print(np.divide(x, y))

[[0.52581715 0.52805281]
 [0.54726368 0.54930212]]

[[0.52581715 0.52805281]
 [0.54726368 0.54930212]]


In [ ]:
# raíz cuadrada
print(np.sqrt(x))

[[10.53565375 10.58300524]
 [11.         11.04536102]]


### Operaciones Estadísticas Básicas

In [ ]:
# Generar un array aleatorio
arr = 10 * np.random.randn(2,5)
print(arr)

[[  6.22566282   1.71715481  -5.97700343  -2.23772028 -13.84514728]
 [ -8.83252814  -4.20879828  -6.57183308   2.08740774  12.24079493]]


In [ ]:
# Calcular la media (promedio) de un array
print(arr.mean())

-1.9402010174617392


In [ ]:
# Calcular el promedio pero en este caso, fila por fila
# eje 0 = columnas
# eje 1 = filas
print(arr.mean(axis = 1))

[-2.82341067 -1.05699137]


In [ ]:
# Calcular el promedio pero en este caso, columna por columna
print(arr.mean(axis = 0))

[-1.30343266 -1.24582173 -6.27441825 -0.07515627 -0.80217617]


In [ ]:
# Creamos array de 10 elementos aleatorios
desordenado = np.random.randn(10)
print(desordenado)

[-0.50481956  0.84723547  0.25878339  1.02775831 -0.29779126 -1.88978477
 -2.4558705  -0.89016547 -0.33669383 -0.37651619]


In [ ]:
# Creamos una copia
ordenado = np.array(desordenado)

# Lo ordenamos
ordenado.sort()
print(ordenado)

[-2.4558705  -1.88978477 -0.89016547 -0.50481956 -0.37651619 -0.33669383
 -0.29779126  0.25878339  0.84723547  1.02775831]


In [ ]:
# Buscando elementos únicos
array = np.array([1,2,1,4,2,1,4,2])
print(np.unique(array))

[1 2 4]


In [ ]:
# OPERACIONES DE CONJUNTO
s1 = np.array(['escritorio','silla','mesa'])
s2 = np.array(['escritorio','silla','lampara'])
print(s1)
print(s2)

['escritorio' 'silla' 'mesa']
['escritorio' 'silla' 'lampara']


In [ ]:
# Intersección
print( np.intersect1d(s1, s2) )

['escritorio' 'silla']


In [ ]:
# Union en 1d
print( np.union1d(s1, s2) )

['escritorio' 'lampara' 'mesa' 'silla']


In [ ]:
# Elementos de s1 que no están en s2
print( np.setdiff1d(s1, s2) )

['mesa']


In [ ]:
# que elementos de s1 están en s2
print( np.in1d(s1, s2) )

[ True  True False]


### Algunas operaciones frecuentes


In [ ]:
# Sumamos todos los elementos de un array
ex1 = np.array([[11,12],[21,22]])
print(np.sum(ex1))

66


In [ ]:
# Sumamos solo una columna
print(np.sum(ex1, axis=0))
# ¿cómo sumaríamos una fila?
print(np.sum(ex1, axis=1))

[32 34]
[23 43]


Reformateando un array

In [ ]:
# Creamos un array
arr = np.arange(20)
print(arr)
arr.shape

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


(20,)

In [ ]:
# Cambiamos su forma
reshped_arr = arr.reshape(4,5)
print(reshped_arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [ ]:
# Transponer o transposicionar un array
ex1 = np.array([[11,12],[21,22]])
print(ex1)
ex1.T



[[11 12]
 [21 22]]


array([[11, 21],
       [12, 22]])

In [ ]:
# WHERE ...
mat = np.random.rand(4,4)
mat

array([[0.48511215, 0.17515303, 0.11769138, 0.07259841],
       [0.51654824, 0.25815866, 0.68641084, 0.45641839],
       [0.06894296, 0.62049899, 0.45399776, 0.06725853],
       [0.47325381, 0.14609518, 0.31266844, 0.6308256 ]])

In [ ]:
# Le paso array condicion, valor si true, valor si false
np.where( mat > 0.5, 1000, -1)

array([[  -1,   -1,   -1,   -1],
       [1000,   -1, 1000,   -1],
       [  -1, 1000,   -1,   -1],
       [  -1,   -1,   -1, 1000]])

In [ ]:
# Comprobar si algun elemento del array es verdadero notar que funciona tanto con número
arr_bools = np.array([ 0,0,0,0,0,0 ])
arr_bools.any()

False

In [ ]:
# Comprobar si todos los elementos del array son True
arr_bools = np.array([ 1,1,0 ])
arr_bools.all()

False

### Uniendo datasets

In [ ]:
K = np.random.randint(low=2,high=50,size=(2,2))
print(K)

print()
M = np.random.randint(low=2,high=50,size=(2,2))
print(M)


[[43 33]
 [45 44]]

[[35 21]
 [ 2 40]]


In [ ]:
# Unimos "apilando" verticalmente
np.vstack((K,M))

array([[43, 33],
       [45, 44],
       [35, 21],
       [ 2, 40]])

In [ ]:
# Unimos "apilando" horizontamente
np.hstack((K,M))

array([[43, 33, 35, 21],
       [45, 44,  2, 40]])

In [ ]:
# Podemos unir concatenando
np.concatenate([K, M], axis = 0)

array([[43, 33],
       [45, 44],
       [35, 21],
       [ 2, 40]])

In [ ]:
np.concatenate([K, M], axis = 1)

array([[43, 33, 35, 21],
       [45, 44,  2, 40]])

<br><br>
## Propagación

Para más detalles:
https://docs.scipy.org/doc/numpy-1.10.1/user/basics.broadcasting.html

In [ ]:
base = np.zeros((4,4))
print(base)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
# Creamos un array unidimensional
row = np.array([1, 0, 2,7])
print(row)
print(row.shape)

[1 0 2 7]
(4,)


In [ ]:
y = base + row
print(y)

[[1. 0. 2. 7.]
 [1. 0. 2. 7.]
 [1. 0. 2. 7.]
 [1. 0. 2. 7.]]


In [ ]:
# Repetimos lo mismo pero ahora a base le sumaremos una columna
col = np.array([[0,1,2,3]])
print(col)

[[0 1 2 3]]


In [ ]:
# Necesitamos "verticalizar" esta "fila"
col = col.T
print(col)

[[0]
 [1]
 [2]
 [3]]


In [ ]:
# Sumemos a base
y = base + col
print(y)

[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]]


In [ ]:
col = np.array([[0,1,2]])
col = col.T
print(col)

[[0]
 [1]
 [2]]


In [ ]:
# Intento hacer una operación de propagación
y = base + col
print(y)

ValueError: operands could not be broadcast together with shapes (4,4) (3,1) 

In [ ]:
arr_x = np.array([4])
print(arr_x)
print("________________")
print(base + arr_x)

[4]
________________
[[4. 4. 4. 4.]
 [4. 4. 4. 4.]
 [4. 4. 4. 4.]
 [4. 4. 4. 4.]]


### Prueba de velocidad!

In [ ]:
from numpy import arange
from timeit import Timer

size    = 1000000
timeits = 1000

nd_array = arange(size)
print( "tipo de dato -> ",type(nd_array) )
print( "Forma -> ", nd_array.shape)


tipo de dato ->  <class 'numpy.ndarray'>
Forma ->  (1000000,)


In [ ]:
# Con la función timer podemos medir, el tiempo que lleva realizar una operación o función

timer_numpy = Timer("nd_array.sum()", "from __main__ import nd_array")
print("Time taken by numpy ndarray: %f seconds" % (timer_numpy.timeit(timeits)))

Time taken by numpy ndarray: 0.680027 seconds


In [ ]:
a_list = list(range(size))
print (type(a_list) )
print( "Forma -> ", len(a_list))

<class 'list'>
Forma ->  1000000


In [ ]:
timer_list = Timer("sum(a_list)", "from __main__ import a_list")
print("Time taken by list:  %f seconds" % (timer_list.timeit(timeits)))

Time taken by list:  5.888654 seconds


### Grabar array a disco / recuperar array de disco

In [ ]:
x = np.array([ 23.23, 24.24] )

In [ ]:
 np.save('array_importante', x)

In [ ]:
recuperado = np.load('array_importante.npy')
print("el array recuperado es: ", recuperado)

el array recuperado es:  [23.23 24.24]
